apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-platform
spec:
  # Number of desired pod replicas
  replicas: 2

  selector:
    matchLabels:
      app: student-platform

  template:
    metadata:
      labels:
        app: student-platform

    spec:
      containers:
        - name: student-platform

          # ⚠️ Replace with your Docker Hub username
          image: techytish/student-platform:latest

          # Container listens on port 8080
          ports:
            - containerPort: 8080